sudo: required
dist: trusty

language: node_js
node_js:
    - '12'

dist: trusty
sudo: false

cache:
    yarn: true
    directories:
        - node_modules

addons:
    chrome: stable

before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'sudo chown root /opt/google/chrome/chrome-sandbox'
    - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'

before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4'
  - 'export PATH="$HOME/.yarn/bin:$PATH"'

install:
    - yarn

script:
    - yarn ci:pipelines
